### PR TITLE
Support 1.20.5

### PR DESCRIPTION
**Pull request by FallenCrystal**
Checks:
  - [x] Fall
  - [x] Vehicle
  - [x] CAPTCHA

~~I've also added some information at encode and decode for debugging. (Avoid incorrectly implementing the codec of packets without us knowing.)~~

### CODE REVIEW

**Comment by jonesdevelopment** [comment]
Thanks a lot for this PR!

**Comment by jonesdevelopment** [comment]
I think 1.20.5 needs some sort of map component ids or something... what is Mojang doing :sob:

**Comment by FallenCrystal** [comment]
> I think 1.20.5 needs some sort of map component ids or something... what is Mojang doing 😭

I forgot about this. But maybe we can confirm that it's no longer like 1.20.4 nbt.

Client will decode two `Array<ComponentChanges>`, one with additional data. The other is the opposite.
Additional data depends on the "PacketCodec<RegistryByteBuf, T>" given by "ComponentChanges".

btw. MapUpdatePacket also has changes that are not included in wiki.vg. It's a bit difficult to figure out these things in a short period of time.

**Comment by jonesdevelopment** [comment]
> It's a bit difficult to figure out these things in a short period of time.

Don't worry, we don't have a deadline.

**Comment by jonesdevelopment** [comment]
Is there any public information about these new components?
I couldn't find anything on wiki.vg, and https://github.com/PrismarineJS/minecraft-data hasn't updated yet.

**Comment by FallenCrystal** [comment]
> Is there any public information about these new components?

There doesn't seem to be any information on how to encode it yet.

**Comment by jonesdevelopment** [comment]
I'll review it once I'm home. Thanks a lot for your contributions!

**Comment by FallenCrystal** [comment]
We forgot to delete the debug information 🤔

**Comment by jonesdevelopment** [comment]
Looks good and works fine for me.

**Pull request merged**
