### PR TITLE
Remove useless biome codec

### PR DESCRIPTION
**Pull request by FallenCrystal**
Only `plains`, `swamps`, and `swamp_hills` biomes remain. Limit the size to ~1000 bytes (for `minecraft:worldgen/biome` type) and shoule be without any side effects.

Wait for #322 to be merged, then update the codec for 1.21.

### CODE REVIEW

**Comment by jonesdevelopment** [comment]
Have you tested this on all versions? (1.16, 1.18, 1.20.4 and 1.20.5)

**Comment by FallenCrystal** [comment]
> Have you tested this on all versions? (1.16, 1.18, 1.20.4 and 1.20.5)

Tested:
  - [x] 1.16.1
  - [x] 1.16.5
  - [x] 1.18.2
  - [x] 1.19.1
  - [x] 1.19.4
  - [x] 1.20.1, 1.20.4, 1.20.5

1.21 tested from #322. Still waiting for it merge to commit.

**Comment by jonesdevelopment** [comment]
@FallenCrystal Ready

**Comment by jonesdevelopment** [comment]
Can't we also remove `swamps` and `swamp_hills`? We only need `plains`, or am I wrong?

**Comment by jonesdevelopment** [comment]
I tried removing `swamps` and `swamp_hills`, and I couldn't join the world anymore. Guess we'll keep it at how you implemented it. It works fine for me — can we merge these changes?

**Comment by FallenCrystal** [comment]
> can we merge these changes?

Yes. If you don't encounter the problem.

**Pull request merged**
