### PR TITLE
Add config & messages files for Chinese Simplified.

### PR DESCRIPTION
**Pull request by FallenCrystal**
In order to make it more fluid and easy to understand. some of the content may differ from the original text.

### CODE REVIEW

**Comment by FallenCrystal** [comment]
oops I forgot to add ci skip (and since the last pull request, that pr defaulted to a draft, I forget to check it..)

**Comment by jonesdevelopment** [comment]
Hi, I'm pretty sure the ISO 639 code for Chinese is `zh` and not `cn`.
Can you check the JVM environment variables for the language code? This is important because automatic language detection won't work if the file names aren't correct.

**Comment by ghost** [comment]
zh_cn

**Comment by jonesdevelopment** [comment]
Thank you!

**Pull request merged**
