### PR TITLE
Recode packet handling on BungeeCord

### PR DESCRIPTION
**Pull request by FallenCrystal**
not sure if there are other issues. i was able to use the 1.8 client to pass authentication and join the server. it is also possible to ping.

### CODE REVIEW

**Comment by jonesdevelopment** [comment]
The packet handling can be simplified, I'll push something to this branch in a few minutes.

**Comment by jonesdevelopment** [comment]
I renamed some fields to follow Java conventions, in-lined some handling and improved some stuff.

**Comment by jonesdevelopment** [comment]
__Testing__
- [x] Too many players per IP check
- [ ] Protocolize
- [ ] MiniMOTD

**Comment by jonesdevelopment** [comment]
image

LGTM — @FallenCrystal What do you think?

**Comment by jonesdevelopment** [comment]
```
16:20:35 [INFO] [Sonar] [fallback] Jones_XX/1.64.12.163 (47) has connected.
16:20:37 [INFO] [Sonar] [fallback] Jones_XX has been verified successfully (1.239s!).
16:20:39 [INFO] [/1.64.12.163:55516] <-> InitialHandler has connected
16:20:39 [INFO] [Jones_XX] <-> ServerConnector [lobby] has connected
```

Pinging should not be a problem with the new version anymore. I tested it on 1.8.9, 1.20.2, and 1.20.4 – since I didn't change anything regarding packets, it should work on every version as it did before.

**Comment by FallenCrystal** [comment]
MiniMOTD and Protocolize are works. however, it has not been tested in production.

**Comment by jonesdevelopment** [comment]
> MiniMOTD and Protocolize are works. however, it has not been tested in production.

@overkidding ?

**Comment by FallenCrystal** [comment]
> image
> 
> LGTM — @FallenCrystal What do you think?

lgtm

**Comment by overkidding** [comment]
> > MiniMOTD and Protocolize are works. however, it has not been tested in production.
> 
> @overkidding ?

we should wait for the night reboot

**Comment by jonesdevelopment** [comment]
image

It's - for some reason - preventing all new connections during an attack

**Comment by jonesdevelopment** [comment]
16:50:39 [INFO] EXCEPTION CAUGHT: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 0a0d0a000d0a515549540a2111

**Comment by overkidding** [comment]
> image
> 
> It's - for some reason - preventing all new connections during an attack

did you patch?

**Comment by overkidding** [comment]
Did you guys test this recoded handler with librelogin?

**Comment by jonesdevelopment** [comment]
@FallenCrystal @overkidding

There are no plugins on the server and I'm using default BungeeCord from https://ci.md-5.net/ and the issue is still appearing.
Could this be a BungeeCord issue?!

image

**Comment by jonesdevelopment** [comment]
> There are no plugins on the server and I'm using default BungeeCord from https://ci.md-5.net/ and the issue is still appearing. Could this be a BungeeCord issue?!

I was trying to investigate https://github.com/jonesdevelopment/sonar/issues/173, but it happens even without Sonar installed?!

**Comment by FallenCrystal** [comment]
> @FallenCrystal @overkidding
> 
> There are no plugins on the server and I'm using default BungeeCord from https://ci.md-5.net/ and the issue is still appearing. Could this be a BungeeCord issue?!
> 
> image

how many throttles do you set? i'm not so sure. but i'm going to try to launch an attack to test it.

**Comment by jonesdevelopment** [comment]
> how many throttles do you set? i'm not so sure. but i'm going to try to launch an attack to test it.

I'm using the default configuration (3000). I'll try it without connection throttling.

**Comment by jonesdevelopment** [comment]
Setting to connection throttle to 0 seems to fix the connection issues.

(without Sonar installed)
image

(with Sonar installed) — I am attacking from my own computer, so my ping went up a little
image

**Comment by overkidding** [comment]
> Could this be a BungeeCord issue?!

Checking BungeeCord commits to see if they changed something in the connection handling classes

**Comment by jonesdevelopment** [comment]
> Checking BungeeCord commits to see if they changed something in the connection handling classes

I updated all the classes in Sonar to match the latest BungeeCord classes: https://github.com/jonesdevelopment/sonar/pull/174/commits/b2bcfcb9ec041bfc55bad8bfb30fb2492ba0c596
The initial connection process looks to be the same, but I don't know if they broke anything in other classes.

**Comment by overkidding** [comment]
> Setting to connection throttle to 0 seems to fix the connection issues.
> 
> (without Sonar installed) image
> 
> (with Sonar installed) — I am attacking from my own computer, so my ping went up a little image

I already had connection throttle to -1 so cannot be that for the #173 issue

**Comment by jonesdevelopment** [comment]
> I already had connection throttle to -1 so cannot be that for the #173 issue

Well, I saw the issue you were facing and I did see a difference in changing it. Pretty sure it wasn't working for you because of the version of Sonar you were using.

**Comment by jonesdevelopment** [comment]
How did pings and connections look like? Did it just close the connection/channel (disconnect) or did you time out?

**Comment by FallenCrystal** [comment]
fully responsed. not installed any plugin.

image

`connection_throttle_limit: 100`

even though my cps was going down when i took the screenshot. but it does respond normally all the time.

**Comment by overkidding** [comment]
> fully responsed. not installed any plugin.
> 
> image
> 
> `connection_throttle_limit: 100`
> 
> even though my cps was going down when i took the screenshot. but it does respond normally all the time.

try with latest protocolize and protocolize legacy data and also librelogin if possible so i can upload everything to the production server this night and test it in production

**Comment by jonesdevelopment** [comment]
These are the default values

```yml
connection_throttle: 3000
connection_throttle_limit: 3
```

**Comment by jonesdevelopment** [comment]
image

With these values, the server blocks every new connection during an attack.

**Comment by overkidding** [comment]
> image
> 
> With these values, the server blocks every new connection during an attack.

are you botting with your local ip or with proxies?

**Comment by jonesdevelopment** [comment]
> are you botting with your local ip or with proxies?

I'm using proxies and I'm attacking my VPS

**Comment by overkidding** [comment]
> > are you botting with your local ip or with proxies?
> 
> I'm using proxies and I'm attacking my VPS

interesting

**Comment by overkidding** [comment]
image
Ping Attacks aren't getting blocked in the current version btw

**Comment by jonesdevelopment** [comment]
"I will likely remove the asynchronous ping handling to avoid these compatibility problems. It's a nice feature and blocks some attacks, but I cannot leave it in a production version if it causes issues with other plugins."

**Comment by overkidding** [comment]
image
When i stop the attack the plugin continues to stay in the mitigation mode instead of sending the mitigated event and stay in waiting

**Comment by jonesdevelopment** [comment]
> When i stop the attack the plugin continues to stay in the mitigation mode instead of sending the mitigated event and stay in waiting

I'll investigate this right now.

**Comment by FallenCrystal** [comment]
> try with latest protocolize and protocolize legacy data and also librelogin if possible so i can upload everything to the production server this night and test it in production

no any exception found. (even under attack)
i haven't configured LibreLogin yet. but JPremium works fine.

**Comment by overkidding** [comment]
> "I will likely remove the asynchronous ping handling to avoid these compatibility problems. It's a nice feature and blocks some attacks, but I cannot leave it in a production version if it causes issues with other plugins."

The previous version too was not blocking them i'm testing on the production server with the async ping handler

**Comment by jonesdevelopment** [comment]
> The previous version too was not blocking them i'm testing on the production server with the async ping handler

To be honest, Sonar doesn't need the ping check. If it breaks stuff, I might as well leave it out. It's an anti-bot, not an anti-ping-spam :shrug:

**Comment by jonesdevelopment** [comment]
I'm working on the attack detection fix right now. Then, I'd like to fix the incompatibilities on BungeeCord. Next is the Geyser fix and if all that is done we can test it thoroughly and I'll release 2.0.16 if everything works as expected.

**Comment by overkidding** [comment]
```
(joinsPerSecond > minPlayers // Check the number of bots/joins per second.
            || verifyingPlayers > minPlayers // Check the number of verifying players.
            || queuedPlayers > minPlayers)
```

the current attack tracker condition doesn't check for pings or CPS only JPS

**Comment by jonesdevelopment** [comment]
> the current attack tracker condition doesn't check for pings or CPS only JPS

That's intended. Sonar doesn't need to enable extra join checks (if configured) if no bot actually tries to join.

**Comment by overkidding** [comment]
> > The previous version too was not blocking them i'm testing on the production server with the async ping handler
> 
> To be honest, Sonar doesn't need the ping check. If it breaks stuff, I might as well leave it out. It's an anti-bot, not an anti-ping-spam 🤷

okok, i asked because sonar-legacy had it before so thats why

**Comment by jonesdevelopment** [comment]
@FallenCrystal Can you update your fork of Sonar (just merge the upstream) so we can test it with the latest version?

**Comment by overkidding** [comment]
> > the current attack tracker condition doesn't check for pings or CPS only JPS
> 
> That's intended. Sonar doesn't need to enable extra join checks (if configured) if no bot actually tries to join.

Ok but just to remember

https://www.youtube.com/watch?v=YVznjAFNRf8

Thats what a ping botnet is able to do so adding this check is not a bad idea in my opinion (it was with the older version of sonar)

**Comment by jonesdevelopment** [comment]
> Thats what a ping botnet is able to do so adding this check is not a bad idea in my opinion (it was with the older version of sonar)

I am aware. That's why you should use something like TCPShield, CosmicGuard, Infinity-Filter, NeoProtect or Papyrus as a DDoS protection service. Sonar's supposed to block bots — my ping checks would prevent this attack, but you can still easily bypass it. It's not worth it in my opinion. If someone is capable of spamming a high amount of connection on a server, it's **only** a matter of whether the server is strong enough to handle these connections or not. There's no point in making an anti-bot **plugin** do that for the server.

**Comment by jonesdevelopment** [comment]
If I hit my server with a botnet, it will die. And a ping check won't change that fact. The VPS simply won't be able to keep up.

**Comment by overkidding** [comment]
> > Thats what a ping botnet is able to do so adding this check is not a bad idea in my opinion (it was with the older version of sonar)
> 
> I am aware. That's why you should use something like TCPShield, CosmicGuard, Infinity-Filter, NeoProtect or Papyrus as a DDoS protection service. Sonar's supposed to block bots — my ping checks would prevent this attack, but you can still easily bypass it. It's not worth it in my opinion. If someone is capable of spamming a high amount of connection on a server, it's **only** a matter of whether the server is strong enough to handle these connections or not. There's no point in making an anti-bot **plugin** do that for the server.

Preventing is always better than healing every antibot nowadays has Ping attacks detection cause its categorized as a "bot attack" even if it is not.

Btw i'm asking for that because i have an AntiDDoS mitigation from my hosting that can be handled with sonar events but without Ping Detection it will be easy to bypass by using just the ping method instead of join and everything its useless

**Comment by jonesdevelopment** [comment]
I promise if the BungeeCord issue is fixed and my new implementation of the asynchronous ping handling works with Protocolize, I will keep it implemented. Is that a deal?

**Comment by overkidding** [comment]
> TCPShield, CosmicGuard, Infinity-Filter, NeoProtect or Papyrus

Most of these services are useless they were able to down my server by downing their proxies 🤣

**Comment by overkidding** [comment]
> I promise if the BungeeCord issue is fixed and my new implementation of the asynchronous ping handling works with Protocolize, I will keep it implemented. Is that a deal?

deal

**Comment by overkidding** [comment]
image
Still there until the reboot it will be under attack 🤣

**Comment by FallenCrystal** [comment]
I'd like to move the conversation to discord. i often have to manually refresh this page to update messages. :(

**Comment by jonesdevelopment** [comment]
> I'd like to move the conversation to discord. i often have to manually refresh this page to update messages. :(

#development (https://jonesdev.xyz/discord)

**Comment by overkidding** [comment]
> I'd like to move the conversation to discord. i often have to manually refresh this page to update messages. :(

No problem for me, my ds handle is the same username as GitHub

**Comment by jonesdevelopment** [comment]
- Resolves https://github.com/jonesdevelopment/sonar/issues/171

**Review by jonesdevelopment — APPROVED** [review]
LGTM; but we should still perform some tests.

**Comment by FallenCrystal** [comment]
maybe we need to remove this.
https://github.com/jonesdevelopment/sonar/blob/main/.github/README.md?plain=1#L47

**Comment by overkidding** [comment]
Running Sonar with this update in production seems to be that there aren't any issues ATM

**Comment by jonesdevelopment** [comment]
> Running Sonar with this update in production seems to be that there aren't any issues ATM

Any issues? Can we close the other 2 issues once this has been merged?

**Comment by jonesdevelopment** [comment]
> maybe we need to remove this.

We'll remove the async ping check for this release, but if async handling works without breaking compatibility, I'll reimplement it later.

**Pull request merged**
