### PR TITLE
1.21 Support

### LINKED ISSUE #321: Feature Request: Minecraft 1.21 Support
### Information

Provide support for Minecraft's latest release: 1.21

__Helpful links__
https://github.com/PaperMC/Velocity/commit/350ea7f31eb40b2c7b28aed0ba070453f48b6e7e
https://wiki.vg/Protocol

### Reason

Support for new Minecraft releases.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by FallenCrystal**
Resolves #321 

Implementation of support for 1.21.

Clients are unable to join the world at this time.

```
Encode packet LoginSuccessPacket (id: 2) with 25 bytes
Trying decode packet LoginAcknowledgedPacket with id 3 and 0 bytes
Encode packet RegistryDataPacket (id: 7) with 1785 bytes
Encode packet RegistryDataPacket (id: 7) with 410 bytes
Encode packet RegistryDataPacket (id: 7) with 4953 bytes
Encode packet RegistryDataPacket (id: 7) with 28906 bytes
Encode packet FinishConfigurationPacket (id: 3) with 1 bytes
Trying decode packet PluginMessagePacket with id 2 and 23 bytes
Trying decode packet ClientSettingsPacket with id 0 and 13 bytes
```

The client doesn't seem to be intending to respond to `FinishConfigurationPacket`. Not sure if it's a timing issue or if we're missing some registry.

Although 1.20.6 already seems to include the 1.21 registry (`painting_variant` & `wolf_variant`). But it's not clear if this is mandatory or SMTH.

### CODE REVIEW

**Comment by jonesdevelopment** [comment]
> Although 1.20.6 already seems to include the 1.21 registry (painting_variant & wolf_variant). But it's not clear if this is mandatory or SMTH.

I tried implementing this locally before, and I ran into the issue that the client couldn't join because these registry entries were missing.

**Comment by jonesdevelopment** [comment]
Minecraft client log:
```
> Errors in registry minecraft:root:
>> Errors in element minecraft:painting_variant:
java.lang.IllegalStateException: Registry must be non-empty
[...]
>> Errors in element minecraft:wolf_variant:
java.lang.IllegalStateException: Registry must be non-empty
[...]
```

**Comment by jonesdevelopment** [comment]
@FallenCrystal Where did you get that from? haha

**Comment by jonesdevelopment** [comment]
The only things left now are correctly loading & implementing it in the registry sync packet.

**Comment by FallenCrystal** [comment]
> @FallenCrystal Where did you get that from? haha

I tried writing the missing registry myself. But not sure if this will work.

btw. I forgot to save. I'll need to update it later.

**Comment by FallenCrystal** [comment]
image

Looks like we need to update the packet ~~and item/blocks id~~.

**Comment by jonesdevelopment** [comment]
We don't need to create some crazy new handler or version-specific packet for now.
... or would it be better to recode the `RegistrySync` packet in order to support more versions out-of-the-box and improve readability/maintainability? To be honest, I don't like the current implementation. It's very hack-y.

**Comment by FallenCrystal** [comment]
> We don't need to create some crazy new handler or version-specific packet for now. ... or would it be better to recode the `RegistrySync` packet in order to support more versions out-of-the-box and improve readability/maintainability? To be honest, I don't like the current implementation. It's very hack-y.

I didn't understand what `out-of-the-box` meant. But compared to distinguishing the difference between versions. It would seem easier to create two different packets. 🤔 
I actually thought so before. But I don't know how to name it. Then mess it up.

**Comment by jonesdevelopment** [comment]
lgtm

**Pull request merged**
